language: node_js
node_js:
- v12.18.3
cache:
  directories:
  - node_modules
env:
  global:
    secure: k8KER/swiO5A4VgP6H+H5akvuWCmY1l6VeslLVX+lvYNFd7gtZgyxd6CF2x0WviRgnh9QYhuHfAjcYB+vS0Ix195hfBQgETgo9A0y6fmjwwEdqcrAY1KmPFFi8fudIUwf9iJhl9xZIHR/x1eigUx69qoqyG4/iFEYnMZvXCXNNMITVYWqCP5CDTiGCEeqzqlbqQ6I/qSaiIoyu/yyuVcxiLtOi9l4sXWgTekfJf3K2AefznObR4Lj5Yhu4T5IFoVeFeOB/jDCIjbTJv371KZrtmZZ4RaTtijkmRzifhsR1z+1/Zo39GBnwGe0SksOTenja5kyKHqdQbsoBqaErr0F5Nbpj25ZgOYzTFKWGvx9Od9GcSvgWuCl3vAXlkb9XXK1FHhG0J4dSZSvnZNmQGB+wPv3tPCMgCj6gZpFfUUkxqNqqHAbVoMFoQ0otH0WPnpi14/Due3WClDU4Zq4a1A14Ct3GVUtoxf3CN603c3D5TVw8l2V0iyWEKx2XnQPwLXOmS03pjUaQqmfP9GAjqlxdvMCBe8UNvGLCTxEEgaxV/YTrawD3oZvlTes2wk2fL4AoBDKNRLoye37xMt3cRLUvNVCcwVeZ2bj/OlY0JgQovtBi7UnPP2xo4H5+sJ4i+FsYOhg/ZIz3R5bmyxgn+tjLhfVCZxO7PEW5ZB4RNo7HU=
install:
- npm install
script: ".scripts/run-tests.sh"
