language: node_js
node_js:
  - v16.15.0
addons:
  chrome: stable
cache:
  directories:
    - node_modules
env:
  matrix:
    - ALKEMIO_SERVER=https://test-alkem.io/api/private/non-interactive/graphql ALKEMIO_SERVER_URL=https://test-alkem.io/api/private/non-interactive/graphql
      ALKEMIO_BASE_URL=https://test-alkem.io MAIL_SLURPER_ENDPOINT=https://test-alkem.io/mailslurper-api/mail
      KRATOS_ENDPOINT=https://test-alkem.io/ory/kratos/public ALKEMIO_SERVER_WS=wss://test.alkem.io/graphql
before_install:
  - npm i -g npm@8.5.5
install:
  - npm install
script:
  - npm run test:organization
  - npm run test:preferences
  - npm run test:roleset
  - npm run test:lifecycle
  - npm run test:contributormanagement
  - npm run test:callouts
  - npm run test:communication
  - npm run test:activity-logs
  - npm run test:storage
  - npm run test:journey
  - npm run test:notifications:callouts
  - npm run test:notifications:messaging
  - npm run test:notifications:community
notifications:
  email:
    recipients:
      - valentin@alkem.io
      - evgeni@alkem.io
    # Options: always, never, change (only if status changes)
    on_success: always
    on_failure: always
